/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function Comments() {
  return (
    <section data-layername="comments" className="flex relative flex-col pt-16 mt-28 max-w-full w-[1310px] max-md:mt-10">
      <header data-layername="title" className="flex z-0 flex-col justify-center w-full text-center max-md:max-w-full">
        <h2 data-layername="جدیدتریندورههایمدرسهمسیر" className="text-4xl font-medium text-gray-700 max-md:max-w-full">
          نظرات هنرجویان ما!
        </h2>
        <p data-layername="جدیدتریندورههایمدرسهمسیر" className="mt-4 text-2xl font-light text-gray-700 max-md:max-w-full">
          نظرات برخی از هنرجویان موفق ما که با دوره‌های مدرسه مسیر به اهداف خود رسیده‌اند.
        </p>
      </header>
    </section>
  );
}

export default Comments;